### ISSUE TITLE
[webui] Remove SASS from cluster

### ISSUE THREAD

**Issue by sharonovd** [tarantool/cartridge#113]
In GitLab by @olegrok on May 30, 2019, 13:20

```
10 warnings and 8 errors generated.
make[1]: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/o.babin/Projects/ib-core/third_party/cluster/webui/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/Users/o.babin/Projects/ib-core/third_party/cluster/webui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/o.babin/Projects/ib-core/third_party/cluster/webui/node_modules/node-sass
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/o.babin/.npm/_logs/2019-05-30T10_06_45_364Z-debug.log
make: *** [webui/node_modules] Error 1
```

Complete build log: https://gist.github.com/olegrok/3e2d72f8e866477648dd887a6494ed99

After downgrade to Node v8 build is successful

**Comment by sharonovd** [comment]
In GitLab by @olegrok on Jun 25, 2019, 13:17

assigned to @KlonD90

**Comment by sharonovd** [comment]
In GitLab by @olegrok on Jul 8, 2019, 10:07

mentioned in merge request tarantool/ib-core/ib-core!721

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jul 22, 2019, 12:38

changed title from **[webui] {-Build fails for NodeJS v12-}** to **[webui] {+Remove SASS from cluster+}**

**Comment by sharonovd** [comment]
In GitLab by @KlonD90 on Jul 22, 2019, 12:49

changed time estimate to 5h

**Comment by sharonovd** [comment]
In GitLab by @r.babaev on Jul 23, 2019, 21:41

mentioned in merge request !150

**Comment by sharonovd** [comment]
In GitLab by @r.babaev on Jul 26, 2019, 12:25

closed via merge request !150

**Comment by sharonovd** [comment]
In GitLab by @r.babaev on Jul 26, 2019, 12:25

mentioned in commit f5f3bdde02758fbe421015e785587dd1a0f7e2bc
